# Generated by Django 5.2.6 on 2025-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/agent')),
                ('name', models.CharField(max_length=120)),
                ('job', models.CharField(max_length=120)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/customer')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('job', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='sity',
            new_name='baths',
        ),
        migrations.AddField(
            model_name='home',
            name='beds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='type',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='images/home'),
        ),
    ]
